### ISSUE TITLE
请问这是一个项目还是不同的项目？

### ISSUE THREAD

**Issue by ybbhai** [mongoding/spring-boot-side#1]

**Comment by mongoding** [comment]
这是一个Spring boot与常见服务端技术，框架，中间件整合学习的项目，每个模块都是一块技术的练习例子，模块与模块间无依赖。这个项目旨在帮助学习Spring boot ，同时基于Spring boot 的特性，方便的去学习，测试，探索服务端领域的各种技术，因为Spring boot 启动方便，配置方便，搭建环境很方便。最初只是在公司内部分享Spring boot，帮助同事学习spring boot及相关技术，现在分享出来，各种练习实例还在完善中，后续会更丰富各种技术实例。最后再强调一下，这是一个辅助学习服务端开发技术的项目。
